/**
 * One-off generator. Run manually with `npx tsx scripts/generate-country-codes.ts`
 * whenever src/lib/geo/data/countries-110m.json is replaced/updated.
 */
import { writeFileSync } from "node:fs"
import countries from "../src/lib/geo/data/countries-110m.json"

type Feature = {
  properties: { ISO_A2_EH?: string; ISO_A2?: string }
}

const featureCollection = countries as unknown as { features: Feature[] }

const codes = new Set<string>()
for (const feature of featureCollection.features) {
  const code = [feature.properties.ISO_A2_EH, feature.properties.ISO_A2].find(
    (value) => value && value !== "-99"
  )
  if (code) codes.add(code)
}

const sorted = [...codes].sort()

const output = `/**
 * Generated by scripts/generate-country-codes.ts — do not edit by hand.
 * Source: src/lib/geo/data/countries-110m.json (Natural Earth 110m Admin-0 Countries).
 */
export const COUNTRY_CODES = ${JSON.stringify(sorted, null, 2)} as const

export type CountryCode = (typeof COUNTRY_CODES)[number]
`

writeFileSync("src/lib/constants/country-codes.ts", output)
console.log(`Wrote ${sorted.length} country codes to src/lib/constants/country-codes.ts`)
